# Generated by Django 4.2.4 on 2023-09-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='Priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Less', 'Less')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='task',
            field=models.CharField(default='', max_length=500),
        ),
    ]
